### PR TITLE
Re-open source plugin

### PR DESCRIPTION
**Pull request by NotNite**
Your project is in violation of the AGPL, and you [have stated](https://github.com/jawslouis/MakePlacePlugin/issues/25#issuecomment-1851228718) this is intentional and you have no plans to open source it. This is breaking the law, and as such I've began to help you with the first steps of re-open sourcing the plugin.

**Making a project closed source does not protect it.** You hurt the ecosystem by not allowing people to benefit or contribute to your source code, and people lose the ability to review your source code or build it themselves. It is completely impossible to trust what is on your machine, even moreso when you refrain from publishing the source. Proprietary applications also do not stop modders from changing the functionality of your code, as clearly shown by us as a community modding FINAL FANTASY XIV.

I created this copy after I made this issue, mainly so I could verify the code was safe for me and my friends' use; but I think it's clear it's better being in the public after your response. Please do not rely on security through obscurity, especially when you are violating the law of a project powered by hundreds of peoples' contributions to open source.

### CODE REVIEW

**Comment by jawslouis** [comment]
While keeping code private doesn't guarantee security, it does make it harder for bad actors to keep up with changes.
You are welcome to debate this matter in the MakePlace discord: https://discord.com/invite/YuvcPzCuhq
If you are able to convince the MakePlace community that keeping the code open-source is better, I will respect the wishes of the community.

**Comment by NotNite** [comment]
Respectfully, I won't attempt to "debate" or "convince" anyone; I'm leaving this pull request and my fork here for others to see and use. It is not a matter of "better"; you are violating a software license and the law. It does not "make it harder" for anyone; Harmony hooking exists, IL modification exists, you can modify plugins from other plugins.

**Comment by nepeat** [comment]
Under the terms of the AGPL, you must provide the source code in an available form. Bad actors is not a valid reason for withholding source code under the license you have agreed to. 

Please reconsider your actions as this is a legal concern.

**Comment by shny-scott** [comment]
when you get sued are you going to tell the lawyers to debate with your discord too

**Comment by irixaligned** [comment]
you're guaranteeing yourself legal issues and mistrust of your userbase by handling this the way you are
you are not gaining anything by doing this -- you are making it harder for your users to know your code is safe, you are making it no less viable for these  invisible "bad actors" to do whatever malicious activity you are convinced exists.
open source projects have been dealing with "bad actors" for years; the entire point of the license is to protect you
but throwing literally all of this aside, what you are doing is outright illegal and i don't think you understand the prior weight of what you are doing.
you are not protecting against bad actors because of how trivial it is to decompile and diff cs projects, you are just making it harder for people to fix/report bugs and verify your code is safe. you are harming literally nobody except your users with good intent
please reconsider this, because this will almost certainly be massively problematic in the future

**Comment by binboupan** [comment]
I don't think anyone is going to come on your Discord to "debate" about being open source or not. If the license is AGPL you absolutely **must** release the source code or you are in violation of the license terms.

**Comment by jarcane** [comment]
I was considering using MakePlace for my next build, but given this news, I'm afraid I will have to decline.

The irony of stealing other people's work without obeying the terms of the exchange, while claiming it is to protect against designs being stolen, is rich enough, but this places my account now in actual risk.

How am I supposed to trust that this plugin is not doing unsafe things that could get me smacked by TOS? MakePlace and similar plugins are already on risky ground as it is, but at least I could trust that it could be audited by others. Now I just have to what? Trust your word that you won't do anything that'll incur S-E's wrath?

If you just want to be proprietary and weird about mods, go back to the Fallout scene or something. This is grossly unethical on about every level.

**Comment by Alluneve** [comment]
hello @jawslouis,

you're playing a rather dangerous game there my friend.
you are openly stating that you're actively breaking the AGPL copyright license and are actively breaking copyright law.

if no one else does it, I will take the time and effort to write up a full copyright claim that MakePlacePlugin and the private repository version of MakePlacePlugin are actively breaking the AGPL with the following resource.

https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice

you have 48 hours to publicise your code,
With wonderful regards,

someone who cares about the principles of copyleft

**Comment by ChrGriffin** [comment]
Hi @jawslouis -- I don't think you understand. This is not optional. This is not a matter for debate. This is not a case of "convincing". Legally, you _must_ make this project open source under AGPL. There is no argument you can make, however eloquent, that can subvert that simple reality.

**Comment by misyltoad** [comment]
I do not play this game, or use this mod, but closed source mods are really a crime against humanity.

There have been many times I have encountered projects that seem interesting on the surface, but were entirely closed source. I don't trust running random binaries on my system.

I was very grateful when newer mod manager projects/stores for other games started to either offer code and decompiles in their UI.

> While keeping code private doesn't guarantee security, it does make it harder for bad actors to keep up with changes.

You are working with .NET, which unless you are using something like il2cpp, is trivially decompilable as seen in this PR. You are not obscuring **anything** at all. You are doing nothing but breaking the license lol.

**Pull request closed without merging**
